### ISSUE TITLE
Ask for a new release

### ISSUE THREAD

**Issue by FabioPinheiro** [sicpa-dlab/didcomm-python#102]
Would it be possible to make a new release soon?
- https://github.com/sicpa-dlab/didcomm-python/pull/94
- https://github.com/sicpa-dlab/didcomm-python/pull/96

It's blocking some agents from being interoperable with other agents that we are building.

**Comment by dkulic** [comment]
Isn't this released in 0.3.2?

**Comment by FabioPinheiro** [comment]
I admit I'm a bit confused right now.
Seems to include those commits yes. Let me close the ticket then
