### ISSUE TITLE
Validating EC keys

### ISSUE THREAD

**Issue by AnomalRoil** [sicpa-dlab/didcomm-python#12]
It seems authlib  isn't supporting key validation for EC keys... 

But in the case of ECDH-1PU, where we do a C(1e,2s) key agreement, key validation is essential (especially in the multi-recipient case) since a malicious static key could otherwise easily cause invalid curve attacks or significantly reduce the entropy of the KEM.

Could we add a key validation function?

**Comment by spivachuk** [comment]
@AnomalRoil We have added a test verifying validation of a wrong EPK point for ECDH-ES:
https://github.com/sicpa-dlab/didcomm-python/pull/17

The wrong point is caught by `cryptography` library which is used by `Authlib`. The actual validation is done by `cryptography.hazmat.backends.openssl.backend.Backend._ec_key_set_public_key_affine_coordinates` method and it raises `ValueError("Invalid EC key.")` in case of an error:
https://github.com/pyca/cryptography/blob/main/src/cryptography/hazmat/backends/openssl/backend.py#L1893

In DIDComm this exception is wrapped to (or replaced with) `MalformedMessageError(MalformedMessageCode.CAN_NOT_DECRYPT)`.
