### ISSUE TITLE
is_did_url only checks for fragment

### ISSUE THREAD

**Issue by dbluhm** [sicpa-dlab/didcomm-python#69]
The `is_did_url` function found in `didcomm.core.utils` checks only for a fragment. Other valid DID URLs, such as `did:example:bob/some/path?some=query` would fail the check.

In the context of DID Doc processing, checking that a value is a DID URL with only  a fragment is valid; however, we should more precisely name the function to clearly mark this intent.

**Comment by victormartinez-work** [comment]
@yvgny
