### ISSUE TITLE
Parsing messages with custom headers fails

### ISSUE THREAD

**Issue by rodolfomiranda** [sicpa-dlab/didcomm-python#79]
`GenericMessage` class expects custom headers in a `custom-headers` field as a `List[Header]` from the plain json/dict, instead of a header in the root msg. Example of a custom header Is `return_route`.

**Comment by dkulic** [comment]
@rodolfomiranda can you provide an example what should be expected behaviour? I am not sure I get that.

**Comment by rodolfomiranda** [comment]
@dkulic 
`custom-headers` is not a defined field in DIDComm message. I understand that this library, as well as the JVM one,  uses that property to embed extra fields that are not listed in the `GenericMessage` class. When reading from a json, or generating a json from that class, the `customer-headers` must be converted from/to properties in the plain json message.
For example a plain json of the form:
```
{
   "id": "abcd",
   "type": "https://didcomm.org/basicmessage/2.0/message",
   "from": "did:example:1234",
   "to": "did.example:4321",
   "body": {'content': 'Hello Bob!'},
   "return_route": "yes",
}
```

should be converted in a GenericMessage object like:
```
(
   "id" = "abcd",
   "type" = "https://didcomm.org/basicmessage/2.0/message",
   "from" = "did:example:1234",
   "to" = "did.example:4321",
   "body": {'content': 'Hello Bob!'},
   "custom-headers": [{"return_route": "yes"}]
)
```
and viceversa when going back from a GenericMessage to the plain json object.

In the python library that treatment of `custom-headers` seems  that was not implemented. However, the JVM library is handling that case correctly. You can see the differences in the following clases:
[didcomm-python](https://github.com/sicpa-dlab/didcomm-python/blob/ac4696c77d7611532598d8800b32d74d681eb0bf/didcomm/message.py)
[didcomm-jvm](https://github.com/sicpa-dlab/didcomm-jvm/blob/main/lib/src/main/kotlin/org/didcommx/didcomm/message/Message.kt)

**Comment by dkulic** [comment]
Thanks. I will take a look.

**Comment by dkulic** [comment]
@rodolfomiranda I have created a PR for this issue. Can you take a look does it solve your problem?
